name: Auto Update Top Repos

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch top 6 repos by stars
        run: |
          repos=$(curl -s "https://api.github.com/users/kh-bikash/repos?per_page=100" \
            | jq -r '. | sort_by(.stargazers_count) | reverse | .[:6] | .[] | "<a href=\"\(.html_url)\"><img src=\"https://github-readme-stats.vercel.app/api/pin/?username=kh-bikash&repo=\(.name)&theme=tokyonight\" height=\"180\"/></a>"')
          echo "$repos" > top_repos.html

      - name: Update README
        run: |
          sed -i '/<!-- Top repos will be dynamically updated via GitHub Action -->/r top_repos.html' README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update top 6 repos" || echo "No changes"
          git push
